IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MZF_TASK]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[MZF_TASK]
GO

CREATE proc [dbo].[MZF_TASK]
AS
EXEC MZF_BACKUP_INVENTORY;
EXEC MZF_UPDATE_STYLE_ORDER;
EXEC MZF_UPDATE_CUSTOMER_POINTS;
EXEC MZF_BACKUP_INVENTORY_GOLD
EXEC MZF_BACKUP_INVENTORY_GRAVEL
EXEC MZF_BACKUP_INVENTORY_MATERIAL
EXEC MZF_BACKUP_INVENTORY_NAKE_DIAMOND
EXEC MZF_BACKUP_INVENTORY_PART
EXEC MZF_BACKUP_INVENTORY_SECOND_GOLD

GO